export const blogPosts = [
  {
    id: "1",
    slug: "enterprise-communication-gesture-recognition",
    title:
      "Revolutionizing Enterprise Communication with AI Gesture Recognition",
    excerpt:
      "In today’s fast-paced enterprise world, communication efficiency is everything. Traditional methods like emails, calls, and meetings often fall short, especially in noisy or hybrid environments. Enter CharadesAI, a cutting-edge AI platform transforming how organizations interact with technology through real-time lip-reading and gesture recognition.",
    author: "Troy McWilliams",
    date: "Nov 5, 2025",
    readTime: "5 min read",
    category: "Product",
    featured: true,
    image: "/images/blog/1.webp",
    thumbnail: "/images/blog/thumb-1.webp",
  },
  {
    id: "2",
    slug: "building-accessible-apps",
    title: "Building Accessible Apps with CharadesAI",
    excerpt:
      "In today's competitive business landscape, accessibility is more than a compliance requirement—it's a strategic advantage. Companies that prioritize inclusive technology not only expand their market reach but also reinforce brand loyalty, employee satisfaction, and operational efficiency.",
    author: "Sean Kingston",
    date: "December 03, 2025",
    readTime: "4 min read",
    category: "Business",
    featured: true,
    image: "/images/blog/2.webp",
    thumbnail: "/images/blog/thumb-2.webp",
  },
  {
    id: "3",
    slug: "lip-reading-accuracy-benchmark",
    title: "Driving Innovation with AI-Powered Silent Communication",
    excerpt:
      "In the modern digital landscape, companies are constantly seeking tools that enhance efficiency, security, and accessibility. CharadesAI enables enterprises to decode silent communication through advanced lip-reading and gesture recognition technology.",
    author: "CharadesAI Team",
    date: "December 15, 2025",
    readTime: "5 min read",
    category: "Product",
    featured: false,
    image: "/images/blog/3.webp",
    thumbnail: "/images/blog/thumb-3.webp",
  },
  {
    id: "4",
    slug: "gesture-recognition-iot",
    title: "Gesture Recognition for IoT Devices",
    excerpt:
      "The Internet of Things (IoT) has revolutionized enterprise operations, enabling smarter workflows, predictive analytics, and automated systems. However, as the number of connected devices grows, so does the need for intuitive, touch-free interaction.",
    author: "CharadesAI Team",
    date: "December 15, 2025",
    readTime: "4 min read",
    category: "Business",
    featured: false,
    image: "/images/blog/4.webp",
    thumbnail: "/images/blog/thumb-4.webp",
  },
  {
    id: "5",
    slug: "edge-ai-deployment",
    title: "Deploying CharadesAI Models on Edge Devices",
    excerpt:
      "Enterprises increasingly demand low-latency, high-performance AI that operates closer to the data source. Whether in manufacturing floors, retail stores, or remote healthcare facilities, edge computing is critical for real-time processing and secure operations.",
    author: "Marcus Johnson",
    date: "Nov 8, 2024",
    readTime: "4 min read",
    category: "Business",
    featured: false,
    image: "/images/blog/5.webp",
    thumbnail: "/images/blog/thumb-5.webp",
  },
  {
    id: "6",
    slug: "multi-language-support",
    title: "Expanding Multi-Language Support to 40+ Languages",
    excerpt:
      "In a global business environment, enterprises must communicate effectively across diverse regions, languages, and cultures. Accessibility and inclusivity are no longer optional—they are essential for customer engagement, workforce productivity, and competitive advantage.",
    author: "Dr. Sarah Chen",
    date: "Nov 1, 2024",
    readTime: "4 min read",
    category: "Business",
    featured: false,
    image: "/images/blog/6.webp",
    thumbnail: "/images/blog/thumb-6.webp",
  },
];
