export const plans = [
  {
    name: "Basic",
    description: "Perfect for small projects and startups",
    monthlyPrice: 29,
    yearlyPrice: 24,
    features: [
      { text: "5,000 API calls/month", included: true },
      { text: "720p video resolution", included: true },
      { text: "Email support", included: true },
      { text: "Basic analytics", included: true },
      { text: "3 languages", included: true },
      { text: "Standard latency", included: true },
      { text: "Webhook integrations", included: false },
      { text: "Custom model training", included: false },
      { text: "SLA guarantee", included: false },
    ],
    cta: "Start Basic",
    popular: false,
  },
  {
    name: "Pro",
    description: "For growing teams and production apps",
    monthlyPrice: 99,
    yearlyPrice: 79,
    features: [
      { text: "50,000 API calls/month", included: true },
      { text: "1080p video resolution", included: true },
      { text: "Priority email support", included: true },
      { text: "Advanced analytics", included: true },
      { text: "Multi-language (10)", included: true },
      { text: "Low latency (<50ms)", included: true },
      { text: "Webhook integrations", included: true },
      { text: "Custom model training", included: true },
      { text: "99.9% SLA", included: true },
    ],
    cta: "Start Pro Plan",
    popular: true,
  },
  {
    name: "Enterprise",
    description: "For large-scale deployments",
    monthlyPrice: null,
    yearlyPrice: null,
    features: [
      { text: "Unlimited API calls", included: true },
      { text: "4K video resolution", included: true },
      { text: "24/7 dedicated support", included: true },
      { text: "Custom analytics", included: true },
      { text: "All 40+ languages", included: true },
      { text: "Ultra-low latency", included: true },
      { text: "Custom integrations", included: true },
      { text: "Private model training", included: true },
      { text: "Custom SLA", included: true },
      { text: "On-premise deployment", included: true },
      { text: "SSO & SAML", included: true },
      { text: "Dedicated account manager", included: true },
    ],
    cta: "Contact Sales",
    popular: false,
  },
];
